-- Table for leads
CREATE TABLE IF NOT EXISTS waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  interest TEXT CHECK (interest IN ('agriculture', 'defense', 'investor', 'other')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Security (RLS)
ALTER TABLE waitlist ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (Public Write)
CREATE POLICY "Public insert" ON waitlist FOR INSERT WITH CHECK (true);

-- Disallow public reads (Private Read)
CREATE POLICY "Admin only read" ON waitlist FOR SELECT USING (false);
